server:
  port: 3000

auth:
  secret: 3Xbackend-dev-secret
  token_expire_hours: 24

storage:
  public_dir: public
  image_dir: public/images
  upload_dir: public/uploads

database:
  # mysql:
  #   user: root
  #   password: zhangxinghui
  #   address: 192.168.80.128
  #   port: 3306
  #   schema: 3X

  mysql:
    user: root
    password: zhangxinghui
    address: 10.2.98.225
    port: 3306
    schema: 3X
